Added rand.h implementation
chermehdi/go-egor pull request #66
Opened 2021-01-12 00:56 UTC by NouemanKHAL

Supported types for now:  
- Numbers: Int, Long, Long Long, Double
- Chars: Char, Lower, Upper, Alpha, Digit
- String

2021-01-12 17:09 UTC, Eroui approved these changes
The  rand.h content is 4 spaces tab, I would go for 2 tabs. Otherwise LGTM

2021-01-12 17:17 UTC, Eroui approved these changes
Few other nit comments.

2021-01-12 17:17 UTC, Eroui commented on templates/resolver.go
> +	void readArgs(int argc, char * argv[]) {
InitSeedFromArgs (Or something like this) is a better name than readArgs which might be a little bit confusing

2021-01-12 17:17 UTC, Eroui commented on templates/resolver.go
> +	std::string String(size_t size, CASE mode = MIXEDCASE) {
What about a alpha numerical strings? I don't think this actually support that?

2021-01-12 20:11 UTC, chermehdi requested changes
Generals comments:

- The indentation should be fixed to 2 spaces
- The class needs some docs on public methods, even if it looks obvious (with specified explicit bounds)

2021-01-12 20:11 UTC, chermehdi commented on templates/resolver.go
> +	Rand(unsigned int _seed) : seed(_seed) {
Why do we have two init methods ?

2021-01-12 20:11 UTC, chermehdi commented on templates/resolver.go
> +	long long LongLong(long long from, long long to) {
either call it `Long` or call it `Int64`

2021-01-12 20:11 UTC, chermehdi commented on templates/resolver.go
> +	char Lower(char from = 'a', char to = 'z') {
Lower shouldn't expect parameters (it's implied in the name)

2021-01-12 20:11 UTC, chermehdi commented on templates/resolver.go
> +	char Upper(char from = 'A', char to = 'Z') {
The same as above.

2021-01-12 20:11 UTC, chermehdi commented on templates/resolver.go
> +	std::string String(size_t size, CASE mode = MIXEDCASE) {
When we talked about this offline I imagined having something like this:

```cpp
const int LOWER = 1
const int UPPER = 1 << 1
const int DIGITS = 1 << 2
// caller would do something like this.
rand.RandString(10, LOWER | UPPER)
```

2021-01-13 21:09 UTC, chermehdi approved these changes

2021-01-14 19:49 UTC, merged